### ISSUE TITLE
Missing LINK and UNLINK methods

### ISSUE THREAD

**Issue by alexmingoia** [jshttp/methods#16]
Largely forgotten but defined in [RFC 2068](https://www.ietf.org/rfc/rfc2068.txt).

**Comment by dougwilson** [comment]
Cool, I'll get them added :) but it's unlikely to fix your issue, as by default the array we export comes from Node.js core, so running this module on Node.js still won't pick up any new methods I add here.

**Comment by dougwilson** [comment]
In other words, if the following command does not list the methods you need, you need to file this issue with Node.js:

    node -pe "require('http').METHODS"

**Comment by dougwilson** [comment]
Looks like there is nothing for us to do, because `require('http').METHODS` doesn't include those two methods, even in the latest version of io.js; you'll notice in our source, all we do is return a lower-cased version of this array.
```
$ iojs -pe 'require("http").METHODS'
[ 'CHECKOUT',
  'CONNECT',
  'COPY',
  'DELETE',
  'GET',
  'HEAD',
  'LOCK',
  'M-SEARCH',
  'MERGE',
  'MKACTIVITY',
  'MKCALENDAR',
  'MKCOL',
  'MOVE',
  'NOTIFY',
  'OPTIONS',
  'PATCH',
  'POST',
  'PROPFIND',
  'PROPPATCH',
  'PURGE',
  'PUT',
  'REPORT',
  'SEARCH',
  'SUBSCRIBE',
  'TRACE',
  'UNLOCK',
  'UNSUBSCRIBE' ]

$ iojs -v
v2.4.0
```

The reason why we're not going to just add it is two-fold:

1. This module currently only exists to provide a shim for `require('http').METHODS` in browser environments, thus at most, our list will be the same as the latest version of Node.js/io.js.
2. The http server within Node.js/io.js will only allow methods through that appear in their `METHODS` array, so simply getting that method added to _the browser-only array_ in this module won't help you use those methods in koa anyway.
