### ISSUE TITLE
Document when http.METHODS suffices

### ISSUE THREAD

**Issue by clark800** [jshttp/methods#18]
It would be helpful to know when adding this dependency is necessary.

**Comment by dougwilson** [comment]
Hi @clark800 , I can certainly get that added to the readme :)

With the current version of this module, it's pretty much if you want to get the list of methods before Node.js had `require('http').METHODS` as an export and you don't want to have a copy of that list in your own code for no reason :)

In a future version, with #15 , this module will end up to be very different, and actually useful. For example, you would be able to ask this module if a given method was defined by IANA, if it is idempotent, safe, or other RFC-defined qualities.

**Comment by dougwilson** [comment]
Oh, and I left out `browserify` as well--if all that is needed is the `require('http').METHODS` export in a program, than simply requiring this module instead of the `http` module will prevent `browserify` from packing the entire `http` shim into the bundle, assuming nothing else required the `http` module.

**Comment by dougwilson** [comment]
Ok, hopefully the documentation is better now :)

**Comment by clark800** [comment]
Thank you!
